# Generated by Django 5.1.4 on 2025-01-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_chatroom_homechatroom_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room',
        ),
        migrations.DeleteModel(
            name='HomeChatroom',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
    ]
